import HeaderMain from '@/components/layout/header'
import '../../globals.css'
import { Inter } from 'next/font/google'
import { getLeagueData, getManagerInfo } from '@/services'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function ManagerLayout({
  children, params
}: {
  children: React.ReactNode, params: any
}) {
  console.log(params.slug);
  const manager: any = await getManagerInfo(params.slug)
  console.log(manager);
  return (
    <html lang="en">
      <body className={inter.className}>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-6 h-6">
            <path strokeLinecap="round" strokeLinejoin="round" d="M15.75 19.5L8.25 12l7.5-7.5" />
        </svg>
        <HeaderMain title={`${manager.name} [${manager.player_first_name} ${manager.player_last_name}]`}/>
        {children}
      </body>
    </html>
  )
}
