import HeaderMain from '@/components/layout/header'
import '../../globals.css'
import { Inter } from 'next/font/google'
import { getLeagueData, getManagerInfo } from '@/services'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function ManagerLayout({
  children, params
}: {
  children: React.ReactNode, params: any
}) {
  console.log(params.slug);
  const manager: any = await getManagerInfo(params.slug)
  console.log(manager);
  return (
    <html lang="en">
      <body className={inter.className}>
        <HeaderMain title={`${manager.name} [${manager.player_first_name} ${manager.player_last_name}]`}/>
        {children}
      </body>
    </html>
  )
}
