'use client'
import HeaderMain from '@/components/layout/header'
import './globals.css'
import { Inter } from 'next/font/google'
import BottomNav from '@/components/layout/bottomNav'
import { getLeagueData } from '@/services'
import { usePathname } from 'next/navigation';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const pathname = usePathname();
  const mapHeader = {
    '/': 'FPLMGM:Summary',
    '/league-a': 'FPLMGM:League A',
    '/league-b': 'FPLMGM:League B',
    '/league-super': 'FPLMGM:Super League'
  }
  let league: any = { league: { name: 'FPLMGM'}};
  return (
    <html lang="en">
      <body className={inter.className}>
        <HeaderMain title={mapHeader[pathname] || 'FPLMGM'}/>
        {children}
        {/* <BottomNav /> */}
      </body>
    </html>
  )
}
